-- 1. ADD MISSING COLUMN TO MEDICAL RECORDS
-- The setup script was missing household_id, which app.js attempts to insert.
ALTER TABLE public.medical_records 
ADD COLUMN IF NOT EXISTS household_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;

-- Update RLS for medical_records to allow household members
DROP POLICY IF EXISTS "Users can manage their own medical records" ON public.medical_records;
CREATE POLICY "Users can manage their own medical records"
ON public.medical_records
FOR ALL
USING (
  (household_id = (SELECT household_id FROM public.user_profiles WHERE id = auth.uid()) AND household_id IS NOT NULL)
  OR user_id = auth.uid()
)
WITH CHECK (
  (household_id = (SELECT household_id FROM public.user_profiles WHERE id = auth.uid()) AND household_id IS NOT NULL)
  OR user_id = auth.uid()
);

-- 2. CREATE WEEKLY MEAL PLAN TABLE
CREATE TABLE IF NOT EXISTS public.weekly_meal_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    household_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    plan_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(household_id)
);

ALTER TABLE public.weekly_meal_plan ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their household meal plan"
ON public.weekly_meal_plan
FOR ALL
USING (
  (household_id = (SELECT household_id FROM public.user_profiles WHERE id = auth.uid()) AND household_id IS NOT NULL)
  OR user_id = auth.uid()
)
WITH CHECK (
  (household_id = (SELECT household_id FROM public.user_profiles WHERE id = auth.uid()) AND household_id IS NOT NULL)
  OR user_id = auth.uid()
);

-- 3. CREATE STOCK ITEMS TABLE
CREATE TABLE IF NOT EXISTS public.stock_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    household_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    quantity NUMERIC DEFAULT 0,
    unit TEXT DEFAULT 'g',
    threshold NUMERIC DEFAULT 0,
    decrement_amount NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.stock_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their household stock items"
ON public.stock_items
FOR ALL
USING (
  (household_id = (SELECT household_id FROM public.user_profiles WHERE id = auth.uid()) AND household_id IS NOT NULL)
  OR user_id = auth.uid()
)
WITH CHECK (
  (household_id = (SELECT household_id FROM public.user_profiles WHERE id = auth.uid()) AND household_id IS NOT NULL)
  OR user_id = auth.uid()
);
