-- ======================================================================
-- PawFeed — Complete Database Schema & Row Level Security Setup
-- Run this script in your Supabase SQL Editor (Dashboard -> SQL Editor -> New Query)
-- ======================================================================

-- 1. Create household_members join table
CREATE TABLE IF NOT EXISTS public.household_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id UUID NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
    role TEXT DEFAULT 'member',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create recipe_favorites table
CREATE TABLE IF NOT EXISTS public.recipe_favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    household_id UUID NOT NULL,
    recipe_id TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, recipe_id)
);

-- 3. Ensure custom_recipes table exists
CREATE TABLE IF NOT EXISTS public.custom_recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    household_id UUID NOT NULL,
    name TEXT NOT NULL,
    ingredients JSONB DEFAULT '[]'::jsonb,
    steps JSONB DEFAULT '[]'::jsonb,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Enable RLS on newly created tables
ALTER TABLE public.household_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipe_favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.custom_recipes ENABLE ROW LEVEL SECURITY;

-- 5. Trigger to automatically sync user_profiles.household_id updates to household_members
CREATE OR REPLACE FUNCTION public.sync_household_members()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.household_id IS NOT NULL THEN
    INSERT INTO public.household_members (user_id, household_id)
    VALUES (NEW.id, NEW.household_id)
    ON CONFLICT (user_id)
    DO UPDATE SET household_id = EXCLUDED.household_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS tr_sync_household_members ON public.user_profiles;
CREATE TRIGGER tr_sync_household_members
AFTER INSERT OR UPDATE OF household_id ON public.user_profiles
FOR EACH ROW EXECUTE FUNCTION public.sync_household_members();

-- 6. Helper function to check if the current authenticated user belongs to a household
-- By using SECURITY DEFINER, this function bypasses RLS on household_members
-- to completely prevent policy recursion while maintaining high performance.
CREATE OR REPLACE FUNCTION public.is_household_member(hh_id UUID)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 
    FROM public.household_members 
    WHERE household_id = hh_id 
      AND user_id = auth.uid()
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER STABLE;

-- 7. Define RLS Policies for household_members itself
DROP POLICY IF EXISTS "household_members_select" ON public.household_members;
CREATE POLICY "household_members_select" ON public.household_members
  FOR SELECT TO authenticated
  USING (
    user_id = auth.uid() OR 
    household_id = (SELECT household_id FROM public.user_profiles WHERE id = auth.uid())
  );

DROP POLICY IF EXISTS "household_members_write" ON public.household_members;
CREATE POLICY "household_members_write" ON public.household_members
  FOR ALL TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- 8. Apply RLS policies using household_members for household-scoped tables
-- Pets
DROP POLICY IF EXISTS "pets_household_policy" ON public.pets;
DROP POLICY IF EXISTS "pets_household_select" ON public.pets;
DROP POLICY IF EXISTS "pets_household_insert" ON public.pets;
DROP POLICY IF EXISTS "pets_household_update" ON public.pets;
DROP POLICY IF EXISTS "pets_household_delete" ON public.pets;

CREATE POLICY "pets_household_policy" ON public.pets
  FOR ALL TO authenticated
  USING (public.is_household_member(household_id))
  WITH CHECK (public.is_household_member(household_id));

-- Feeding Logs
DROP POLICY IF EXISTS "feeding_logs_household" ON public.feeding_logs;
CREATE POLICY "feeding_logs_household" ON public.feeding_logs
  FOR ALL TO authenticated
  USING (public.is_household_member(household_id))
  WITH CHECK (public.is_household_member(household_id));

-- Care Tasks
DROP POLICY IF EXISTS "care_tasks_household" ON public.care_tasks;
CREATE POLICY "care_tasks_household" ON public.care_tasks
  FOR ALL TO authenticated
  USING (public.is_household_member(household_id))
  WITH CHECK (public.is_household_member(household_id));

-- Medical Records
DROP POLICY IF EXISTS "medical_records_household" ON public.medical_records;
DROP POLICY IF EXISTS "Users can manage their own medical records" ON public.medical_records;
CREATE POLICY "medical_records_household" ON public.medical_records
  FOR ALL TO authenticated
  USING (public.is_household_member(household_id))
  WITH CHECK (public.is_household_member(household_id));

-- Medical Reports
DROP POLICY IF EXISTS "medical_reports_household" ON public.medical_reports;
DROP POLICY IF EXISTS "Users can manage their own medical reports" ON public.medical_reports;
CREATE POLICY "medical_reports_household" ON public.medical_reports
  FOR ALL TO authenticated
  USING (public.is_household_member(household_id))
  WITH CHECK (public.is_household_member(household_id));

-- Weight History
DROP POLICY IF EXISTS "weight_history_household" ON public.weight_history;
CREATE POLICY "weight_history_household" ON public.weight_history
  FOR ALL TO authenticated
  USING (public.is_household_member(household_id))
  WITH CHECK (public.is_household_member(household_id));

-- Pet Gallery
DROP POLICY IF EXISTS "pet_gallery_household" ON public.pet_gallery;
CREATE POLICY "pet_gallery_household" ON public.pet_gallery
  FOR ALL TO authenticated
  USING (public.is_household_member(household_id))
  WITH CHECK (public.is_household_member(household_id));

-- Mood Logs
DROP POLICY IF EXISTS "mood_logs_household" ON public.mood_logs;
CREATE POLICY "mood_logs_household" ON public.mood_logs
  FOR ALL TO authenticated
  USING (public.is_household_member(household_id))
  WITH CHECK (public.is_household_member(household_id));

-- Sleep Logs
DROP POLICY IF EXISTS "sleep_logs_household" ON public.sleep_logs;
CREATE POLICY "sleep_logs_household" ON public.sleep_logs
  FOR ALL TO authenticated
  USING (public.is_household_member(household_id))
  WITH CHECK (public.is_household_member(household_id));

-- Stock Items
DROP POLICY IF EXISTS "stock_items_household" ON public.stock_items;
CREATE POLICY "stock_items_household" ON public.stock_items
  FOR ALL TO authenticated
  USING (public.is_household_member(household_id))
  WITH CHECK (public.is_household_member(household_id));

-- Expenses
DROP POLICY IF EXISTS "expenses_household" ON public.expenses;
CREATE POLICY "expenses_household" ON public.expenses
  FOR ALL TO authenticated
  USING (public.is_household_member(household_id))
  WITH CHECK (public.is_household_member(household_id));

-- Custom Recipes
DROP POLICY IF EXISTS "custom_recipes_household" ON public.custom_recipes;
CREATE POLICY "custom_recipes_household" ON public.custom_recipes
  FOR ALL TO authenticated
  USING (public.is_household_member(household_id))
  WITH CHECK (public.is_household_member(household_id));

-- Weekly Meal Plan
DROP POLICY IF EXISTS "Users can manage their household meal plan" ON public.weekly_meal_plan;
CREATE POLICY "weekly_meal_plan_household" ON public.weekly_meal_plan
  FOR ALL TO authenticated
  USING (public.is_household_member(household_id))
  WITH CHECK (public.is_household_member(household_id));

-- Recipe Favorites
DROP POLICY IF EXISTS "recipe_favorites_household" ON public.recipe_favorites;
CREATE POLICY "recipe_favorites_household" ON public.recipe_favorites
  FOR ALL TO authenticated
  USING (public.is_household_member(household_id))
  WITH CHECK (public.is_household_member(household_id));

-- Medications (meds)
DROP POLICY IF EXISTS "meds_household" ON public.meds;
CREATE POLICY "meds_household" ON public.meds
  FOR ALL TO authenticated
  USING (public.is_household_member(household_id))
  WITH CHECK (public.is_household_member(household_id));

-- Vet Logs (vet_logs)
DROP POLICY IF EXISTS "vet_logs_household" ON public.vet_logs;
CREATE POLICY "vet_logs_household" ON public.vet_logs
  FOR ALL TO authenticated
  USING (public.is_household_member(household_id))
  WITH CHECK (public.is_household_member(household_id));

-- 9. Add all shared tables to the realtime publication
-- In Supabase, this enables real-time broadcast via postgres_changes.
ALTER PUBLICATION supabase_realtime ADD TABLE public.pets;
ALTER PUBLICATION supabase_realtime ADD TABLE public.feeding_logs;
ALTER PUBLICATION supabase_realtime ADD TABLE public.care_tasks;
ALTER PUBLICATION supabase_realtime ADD TABLE public.medical_records;
ALTER PUBLICATION supabase_realtime ADD TABLE public.weight_history;
ALTER PUBLICATION supabase_realtime ADD TABLE public.pet_gallery;
ALTER PUBLICATION supabase_realtime ADD TABLE public.mood_logs;
ALTER PUBLICATION supabase_realtime ADD TABLE public.sleep_logs;
ALTER PUBLICATION supabase_realtime ADD TABLE public.stock_items;
ALTER PUBLICATION supabase_realtime ADD TABLE public.expenses;
ALTER PUBLICATION supabase_realtime ADD TABLE public.custom_recipes;
ALTER PUBLICATION supabase_realtime ADD TABLE public.weekly_meal_plan;
ALTER PUBLICATION supabase_realtime ADD TABLE public.recipe_favorites;
ALTER PUBLICATION supabase_realtime ADD TABLE public.meds;
ALTER PUBLICATION supabase_realtime ADD TABLE public.vet_logs;
ALTER PUBLICATION supabase_realtime ADD TABLE public.community_comments;
